RRC: clang does not support designated initializers for non-POD types
This fixes all errors similar to this one

srsLTE/srsue/src/stack/rrc/rrc.cc:2681:17: error: no matching constructor for initialization of 'srslte::pdcp_config_t'
  pdcp_config_t pdcp_cfg = {.bearer_id    = srb_cnfg->srb_id,
                ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
srsLTE/lib/include/srslte/common/interfaces_common.h:80:3: note: candidate constructor not viable: cannot convert argument of incomplete type 'void' to 'uint8_t' (aka 'unsigned char') for 1st argument
  pdcp_config_t(uint8_t              bearer_id_,
  ^
srsLTE/lib/include/srslte/common/interfaces_common.h:77:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 5 were provided
class pdcp_config_t
      ^
srsLTE/lib/include/srslte/common/interfaces_common.h:77:7: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 5 were provided