rf_helper.h: Avoid compilation error using strncpy
gcc 10.1.0 seems to be generating a false positive here, l'ets avoid
compilation failing due to that.

/srsLTE/lib/src/phy/rf/rf_helper.h:85:5: error: ‘strncpy’ output may
be truncated copying 255 bytes from a string of length 255 [-Werror=stringop-truncation]
   85 |     strncpy(param_dst, config_str, RF_PARAM_LEN)